### ISSUE TITLE
Exists Operation Throws TypeError 

### ISSUE THREAD

**Issue by medelman17** [graphcool/prisma-binding#152]
The following code, which used to work fine, now throws a TypeError: "cannot read property 'call' of undefined": 

`const exists = await ctx.db.exists.Media({ localSource })`

Stack: prisma/1.7.4 (darwin-x64) node-v9.8.0

**Comment by marktani** [comment]
Thanks for the bug report! 🙂

Can you share the following details:

* datamodel
* value of `localSource`
* version of `prisma-binding`

A minimal reproduction repo would be very helpful as well!

**Comment by medelman17** [comment]
Sure, but before I do, let me just note that if I change the `super` to `self` in following code in the generated `prisma.js` file, it works as expected: 

```
      Media(where) {
        return super.existsDelegate("query", "medias", { where }, {}, "{ id }");
      },
```

**Comment by medelman17** [comment]
This issue may be solved by undertaking the following steps: 

1. Install `graphql-cli@2.16.0-beta.6` & `prisma-binding@1.6.0-beta.16` (global installations of `graphql-cli` may need to be upgraded, too).

2. In `prisma.yml`, add `graphql codegen` as a post-deploy hook.  

3. In `.graphqlconfig.yml`, configure `codegen` to use `prisma-binding` as its generator. 

4. Import `{ Prisma }`  from "../generated/prisma"` (instead of `prisma-binding`). 

5. Remove `typeDefs` from the options supplied when instantiating `Prisma`

6. Redeploy Prisma and/or run `graphql codegen`

Examples: 

_prisma.yml_
```
endpoint: **your endpoint**

datamodel:
  - schema.graphql

secret: **your secret**

hooks:
  post-deploy:
    - echo "Deployment Finished..."
    - graphql get-schema --project prisma
    - graphql codegen
```

_.graphqlconfig.yml_
```
projects:
  prisma:
    schemaPath: path/to/generated/schema.graphql
    extensions:
      prisma: path/to/prisma.yml
      codegen:
        generator: prisma-binding
        output:
          binding: path/to/generated/prisma.js
        language: javascript
```

_maybe schema.js_
```
import { Prisma } from "./path/to/generated/prisma";

export const db = new Prisma({
  // typeDefs: 'path/to/generated/schema.graphql',
  endpoint: process.env.PRISMA_ENDPOINT,
  secret: process.env.PRISMA_SECRET,
...
});
```
